### PR TITLE
Add script for converting trusted setups

### PR DESCRIPTION
**Pull request by jtraglia**
As discussed on our call, this script will convert the trusted setup from the spec to the format that c-kzg uses.

### CODE REVIEW

**Comment by asn-d6** [comment]
I would wait until the official trusted setup comes out before we merge this? To make sure that it corresponds to the final version of the json format.

**Comment by jtraglia** [comment]
That works. Right now it conforms to the current format. It will need some minor changes for the new format.

**Comment by jtraglia** [comment]
Depends on #377 to get the new trusted setup.

**Review by asn-d6 — APPROVED** [review]
Looks great!

**Pull request merged**
