### PR TITLE
Add test for compute_powers

### PR DESCRIPTION
**Pull request by jtraglia**
Adds a simple test case for compute_powers to ensure it's working properly.

### CODE REVIEW

**Comment by jtraglia** [comment]
Also, it seems that `compute_powers` is computing one extra power than it needs to.

https://github.com/ethereum/c-kzg-4844/blob/1e7353c435face227c4037b929db21373013c3ba/src/c_kzg_4844.c#L883-L889

It assigns the power, then computes the next power. The last one won't be assigned to anything.

**Comment by jtraglia** [comment]
Okay, I made some changes to `compute_powers` that I think will speed things up.

@asn-d6 what do you think about this? I think the spec could be improved here.

**Comment by jtraglia** [comment]
Hmm something's a little wonky with node.js. Passes all of the tests but fails at the end.

```
Test Suites: 1 passed, 1 total
Tests:       9 passed, 9 total
Snapshots:   0 total
Time:        7.379 s
Ran all test suites.
free(): invalid next size (fast)
Aborted (core dumped)
error Command failed with exit code 134.
```

Will investigate.

**Comment by asn-d6** [comment]
> Okay, I made some changes to `compute_powers` that I think will speed things up.
> 
> @asn-d6 what do you think about this? I think the spec could be improved here.

Hmm, so one field multiplication is about 40 nanoseconds. I think it doesn't make sense to optimize for this kind of gain. I would suggest we stick with the spec logic given that it's simpler and has less special case checks.

**Comment by jtraglia** [comment]
Okay sounds good. Will revert.

**Comment by asn-d6** [comment]
LGTM!

**Pull request merged**
