### PR TITLE
Fully free FFTSettings

### PR DESCRIPTION
**Pull request by benjaminion**
Plug a little memory leak associated with `FFTSettings`.

### CODE REVIEW

**Comment by xrchz** [comment]
Nice find!

It might be good to use different naming schemes for `free_fft_settings` and `free_kzg_settings`, since now the former also frees the passed pointer but the latter does not. Alternatively manually call this free outside the function (at its sole call site) instead.

**Comment by benjaminion** [comment]
Valgrind is my friend :)

Yes, it could be cleaner. Mostly just keen to see if it resolves the issues for the Java API fuzzing. I'm happy for you to tidy it up as you see fit.

**Comment by xrchz** [comment]
My alt: #39 
If that also looks good to you I'll use it.

**Comment by benjaminion** [comment]
Heh, looks good. I did exactly the same once I'd decided not to be so lazy.

**Pull request closed without merging**
