### PR TITLE
Update java bindings to use runtime field count

### PR DESCRIPTION
**Pull request by jtraglia**
This PR updates the Java bindings to work with runtime field counts.

### CODE REVIEW

**Comment by jtraglia** [comment]
@StefanBratanov do we need to expose a `getBytesPerBlob()` method?

**Comment by StefanBratanov** [comment]
> @StefanBratanov do we need to expose a `getBytesPerBlob()` method?

We already do right in CKZG4844JNI. Or you mean have it as a native method?

**Comment by StefanBratanov** [comment]
Can change actually the javadoc of `getFieldElementsPerBlob()` as well since it is not correct.

**Comment by jtraglia** [comment]
> > @StefanBratanov do we need to expose a `getBytesPerBlob()` method?
> 
> We already do it in CKZG4844JNI right? Or you mean have it as a native method?

Ah that's right. I forgot it was [in CKZG4844JNI](https://github.com/ethereum/c-kzg-4844/blob/fbef59a3f9e8fa998bdb5069d212daf83d586aa5/bindings/java/src/main/java/ethereum/ckzg4844/CKZG4844JNI.java#L83-L90). It doesn't need to be a native method.

**Comment by StefanBratanov** [comment]
> > Can change actually the javadoc of `getFieldElementsPerBlob()` as well since it is not correct.
> 
> Fixed in [072cb97](https://github.com/ethereum/c-kzg-4844/pull/364/commits/072cb9707962efe1484cadf834c4d3312bc79db9). Happy to make changes if it doesn't read well.

Looks good. Thanks. Happy to merge.

**Review by asn-d6 — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
