### PR TITLE
Generate coverage report

### PR DESCRIPTION
**Pull request by jtraglia**
* Generate coverage report for the tests.
* There is a generated html report available via CI artifact.
* For now, this doesn't fail if it's not 100% covered.
* You should be able to run `make test_cov` for a detailed view.

### CODE REVIEW

**Comment by jtraglia** [comment]
It's not very obvious, but there's an artifact (`coverage.html`) that gets uploaded. Find it on this page:

* https://github.com/ethereum/c-kzg-4844/actions/runs/4059028996

**Comment by jtraglia** [comment]
@asn-d6 what do you think about this?

**Comment by asn-d6** [comment]
> 

Really cool!

**Comment by jtraglia** [comment]
Also, it's showing that there isn't a failing case for the `blst_p1_on_curve` check:

image

**Pull request merged**
