### PR TITLE
Fix g1_lincomb() to work with zero points as input

### PR DESCRIPTION
**Pull request by asn-d6**
Implements the weed out strategy from https://github.com/ethereum/c-kzg-4844/issues/138#issue-1588962093

### CODE REVIEW

**Comment by xrchz** [comment]
Why rename to `point_out`? Don't think this is necessary but if you want to do it also update the doc comment.

**Comment by asn-d6** [comment]
> Why rename to `point_out`? Don't think this is necessary but if you want to do it also update the doc comment.

Ah I renamed so that it's not called the same as the goto `out` label.

**Comment by asn-d6** [comment]
Updated doc in 3e0dfd8

**Comment by dankrad** [comment]
I think this is fine and not super complicated.

However, we should check if the blst MSM has ever been audited. If it hasn't been, it might be useless to implement this strategy:
 - for the batch verification code, we should then probably always use plain multiplication
 - for the commitment/proof construction code, we don't have to use this as the trusted setup will never have identity elements.

**Comment by dankrad** [comment]
BLST Pippenger has not been audited. I suggest therefore that we change our strategy to what I wrote above.

**Comment by xrchz** [comment]
> > Why rename to `point_out`? Don't think this is necessary but if you want to do it also update the doc comment.
> 
> Ah I renamed so that it's not called the same as the goto `out` label.

This is inconsistent with the rest of the file: I think we usually use `out` for both return argument and label.

**Comment by asn-d6** [comment]
> I think this is fine and not super complicated.
> 
> However, we should check if the blst MSM has ever been audited. If it hasn't been, it might be useless to implement this strategy:
> 
>     * for the batch verification code, we should then probably always use plain multiplication
> 
>     * for the commitment/proof construction code, we don't have to use this as the trusted setup will never have identity elements.

OK that makes sense. Closing this PR for now, and will open a new one with this strategy.

Thanks all!

**Pull request closed without merging**
