### PR TITLE
feat: add serde impls to Blob and Bytes48

### PR DESCRIPTION
**Pull request by Rjected**
This adds serde `Serialize` and `Deserialize` implementations that work with a `0x` prefix.

### CODE REVIEW

**Comment by asn-d6** [comment]
Hey. Can you tell us why you need the serde impls and the from_hex() is not sufficient for your needs? Is it just for testing purposes?

**Comment by Rjected** [comment]
> Hey. Can you tell us why you need the serde impls and the from_hex() is not sufficient for your needs? Is it just for testing purposes?

I'd like to use `Blob` and `Bytes48` in other types in reth and not have to write a manual `Serialize` or `Deserialize` impl for these higher level types, for example using this branch lets us `derive` here:
https://github.com/paradigmxyz/reth/blob/bfa130d1875f1e1510e181e09fced33578d70563/crates/primitives/src/transaction/eip4844.rs#L547-L557

We provide these traits on almost all basic types so it's possible for API consumers to use the serde ecosystem in their own applications. With the serde impl, it would also become possible to use these types directly for RPC serialization instead of requiring conversion to another type that uses `Bytes`:
https://github.com/paradigmxyz/reth/blob/bfa130d1875f1e1510e181e09fced33578d70563/crates/rpc/rpc-types/src/eth/engine/payload.rs#L215-L221

**Review by jtraglia — COMMENTED** [review]
Makes sense. For completeness, could we add serde impls for `Bytes32` too?

**Comment by Rjected** [comment]
> Makes sense. For completeness, could we add serde impls for Bytes32 too?

just added!

**Review by jtraglia — APPROVED** [review]
Great. Thanks for adding that. LGTM 👍

**Review by asn-d6 — APPROVED** [review]

**Comment by asn-d6** [comment]
Thanks!

**Pull request merged**
