### PR TITLE
Add workflow to publish python package

### PR DESCRIPTION
**Pull request by jtraglia**
This PR adds a new workflow which publishes the python module to PyPI.

Marking this as a draft until devops has added the API key to GitHub secrets.

@kclowes (from EF snake charmers team) requested this.

### CODE REVIEW

**Comment by jtraglia** [comment]
Okay, the API key should be in the repo's secrets now. Ready for review.

**Comment by jtraglia** [comment]
Hmm I'm going to convert this to use `ciwheelhouse` which should simplify things a bit.

**Review by kclowes — APPROVED** [review]
This looks good to me @jtraglia. Thank you! I'm getting a deprecation warning from using `python3 setup.py install` [here](https://github.com/ethereum/c-kzg-4844/blob/main/bindings/python/Makefile#L9), but I did verify it's working! When I swapped that line locally with `python -m build` (the newer syntax), I was getting a `clang` error and haven't had time to debug. I can dig in more on Monday if you want, but it's just a deprecation warning so I think this is good to merge as-is. /cc @fselmo

**Comment by jtraglia** [comment]
Hey @kclowes, thanks for the review! I think I'm okay with a deprecation warning.

I'll plan to merge this on Monday & make a new release to test it soon after.

**Pull request merged**
