### PR TITLE
Rebuild of Nodejs Bindings

### PR DESCRIPTION
**Pull request by matthewkeil**
Follow-up to PR #147 and related to Issue #153, Issue #149 and Issue #118.

## Inclusions
- #153 - Polishes the node bindings
- Unit tests for arg and return types
- `tools` folder with utils, dev, publish scripts
- #149 - Updated files/filestructure in `bindings/node.js`
- #118 - Add `-fPIC` to linux build flag

**Notes:**
- I am adding some additional unit tests for the bindings today but those should not affect the code as I was running the code on `watch` while I worked and saw the errors being thrown

### CODE REVIEW

**Comment by matthewkeil** [comment]
I just saw the workflow fail and am updating that now.  Will push a commit in two shakes.  Just want to test it first

**Comment by matthewkeil** [comment]
I added the `-fPIC` and the library builds fine using npm on ubuntu.  But now there is an error when the tests run `symbol lookup error: c-kzg-4844/bindings/node.js/build/Release/kzg_bindings.node: undefined symbol: blst_p1_uncompress`.

The CI using ubuntu was working with the `make` commands and only broke after the code changes and switching to npm command.  I can try to move back to the make command for this PR and can perhaps do the npm fix on a subsequent PR to not hold things up.

In the mean time I added a matrix strategy to the workflow to test the bindings against `mac/windows/linux` for node versions `12, 14, 16, 17, 18` so we can see build/test results against a few different environments until things are stable

**Comment by dapplion** [comment]
To ease reviews I would close this PR and split into progressive chunks:

_non-core logic_
- Update CI workflow(s)
- Add eslint
- Update misc config files
- Expand tests against current logic in `main`

_core logic_
- Polish bindings with min set of changes for the items https://github.com/ethereum/c-kzg-4844/issues/153
- Then, propose re-write

**Comment by matthewkeil** [comment]
Closing this and will reopen as several separate PR's

**Pull request closed without merging**
